import type { Metadata } from 'next';
import React from 'react';
import Link from 'next/link';
import { FileText, CheckCircle, AlertTriangle, Scale, Code, ShieldCheck, Mail, ArrowLeft, HeartHandshake } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms of Service and conditions for using Color Magic, an open-source color palette generator and designer suite.',
  alternates: { canonical: '/terms' },
  openGraph: {
    title: 'Terms of Service | Color Magic',
    description: 'Terms and conditions for using Color Magic.',
    url: '/terms',
  },
};

export default function TermsOfServicePage() {
  const lastUpdated = 'February 26, 2025';

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16 space-y-12">
      {/* Header */}
      <div className="text-center space-y-4">
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 text-xs font-bold text-slate-500 hover:text-purple-600 transition-colors mb-2"
        >
          <ArrowLeft className="w-3.5 h-3.5" /> Back to Home
        </Link>
        <div className="flex justify-center">
          <span className="inline-flex items-center gap-1.5 px-3.5 py-1 bg-pink-50 text-pink-600 rounded-full border border-pink-100 text-xs font-bold shadow-2xs">
            <FileText className="w-4 h-4 text-pink-600" /> Legal &amp; Agreement
          </span>
        </div>
        <h1 className="text-4xl sm:text-5xl font-black tracking-tight text-slate-900">
          Terms of{' '}
          <span className="bg-gradient-to-r from-purple-600 to-pink-500 bg-clip-text text-transparent">
            Service
          </span>
        </h1>
        <p className="text-slate-500 text-sm max-w-xl mx-auto">
          Please read these terms and conditions carefully before using the Color Magic application and associated tools.
        </p>
        <p className="text-xs font-mono text-slate-400">Last updated: {lastUpdated}</p>
      </div>

      {/* Summary Highlight Box */}
      <div className="bg-gradient-to-r from-purple-50 via-pink-50 to-purple-50 border border-pink-100 rounded-3xl p-6 sm:p-8 flex flex-col sm:flex-row items-start sm:items-center gap-5 shadow-xs">
        <div className="w-14 h-14 rounded-2xl bg-white text-pink-500 flex items-center justify-center shrink-0 shadow-md">
          <HeartHandshake className="w-8 h-8" />
        </div>
        <div className="space-y-1">
          <h3 className="text-lg font-black text-slate-900">Free, Open &amp; Developer-Friendly</h3>
          <p className="text-slate-600 text-xs sm:text-sm leading-relaxed">
            Color Magic is an open-source project licensed under the <strong>MIT License</strong>. You are free to use our generated palettes, gradients, and CSS snippets for personal, commercial, and client projects without royalties or restrictions.
          </p>
        </div>
      </div>

      {/* Detailed Sections */}
      <div className="space-y-8">
        {/* 1. Acceptance of Terms */}
        <section className="bg-white border border-slate-100 rounded-3xl p-8 shadow-xs space-y-4">
          <h2 className="text-2xl font-extrabold text-slate-900 flex items-center gap-2">
            <CheckCircle className="w-6 h-6 text-emerald-500" /> 1. Acceptance of Terms
          </h2>
          <p className="text-slate-600 text-sm leading-relaxed">
            By accessing or using the Color Magic website, tools, or APIs located at <strong>colormagic.techkreative.com</strong> (the &quot;Service&quot;), provided by <strong>TechKreative</strong>, you agree to be bound by these Terms of Service. If you disagree with any part of these terms, you may not access the Service.
          </p>
        </section>

        {/* 2. Open-Source & License */}
        <section className="bg-white border border-slate-100 rounded-3xl p-8 shadow-xs space-y-4">
          <h2 className="text-2xl font-extrabold text-slate-900 flex items-center gap-2">
            <Code className="w-6 h-6 text-purple-600" /> 2. Software License &amp; Intellectual Property
          </h2>
          <p className="text-slate-600 text-sm leading-relaxed">
            The source code of Color Magic is licensed under the terms of the <strong>MIT License</strong>.
          </p>
          <div className="bg-slate-50 p-4 rounded-2xl border border-slate-100 font-mono text-xs text-slate-700 leading-relaxed">
            Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files, to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software.
          </div>
          <p className="text-slate-600 text-sm leading-relaxed">
            <strong>Color Outputs &amp; Palettes:</strong> Any color combinations, palette exports, CSS gradient codes, or contrast calculations generated by you using Color Magic are your property and may be utilized freely in any commercial, artistic, or personal creation.
          </p>
        </section>

        {/* 3. User Accounts & Google Authentication */}
        <section className="bg-white border border-slate-100 rounded-3xl p-8 shadow-xs space-y-4">
          <h2 className="text-2xl font-extrabold text-slate-900 flex items-center gap-2">
            <ShieldCheck className="w-6 h-6 text-pink-500" /> 3. User Accounts &amp; Authentication
          </h2>
          <p className="text-slate-600 text-sm leading-relaxed">
            We provide Google OAuth login so users can save favorites and sync them across devices:
          </p>
          <ul className="space-y-2 text-sm text-slate-600 list-disc list-inside pl-2">
            <li>You agree to use authentic Google accounts and maintain the security of your login credentials.</li>
            <li>You may not use the Service for any unauthorized, automated scraping, or abusive purpose that degrades service stability for other users.</li>
            <li>We reserve the right to suspend access to any user account found engaging in abusive activity or denial-of-service attacks.</li>
          </ul>
        </section>

        {/* 4. Acceptable Use Policy */}
        <section className="bg-white border border-slate-100 rounded-3xl p-8 shadow-xs space-y-4">
          <h2 className="text-2xl font-extrabold text-slate-900 flex items-center gap-2">
            <Scale className="w-6 h-6 text-blue-500" /> 4. Acceptable Use
          </h2>
          <p className="text-slate-600 text-sm leading-relaxed">
            When interacting with Color Magic, you agree NOT to:
          </p>
          <ul className="space-y-2 text-sm text-slate-600 list-disc list-inside pl-2">
            <li>Attempt to interfere with or compromise system integrity or server infrastructure.</li>
            <li>Use automated scripts to overload our API endpoints.</li>
            <li>Impersonate any person or entity, or falsely state or misrepresent your affiliation with TechKreative or Color Magic.</li>
          </ul>
        </section>

        {/* 5. Disclaimer of Warranties */}
        <section className="bg-white border border-slate-100 rounded-3xl p-8 shadow-xs space-y-4">
          <h2 className="text-2xl font-extrabold text-slate-900 flex items-center gap-2">
            <AlertTriangle className="w-6 h-6 text-amber-500" /> 5. Disclaimer of Warranties &amp; Limitation of Liability
          </h2>
          <p className="text-slate-600 text-sm leading-relaxed">
            THE SERVICE IS PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
          </p>
          <p className="text-slate-600 text-sm leading-relaxed">
            IN NO EVENT SHALL TECHKREATIVE OR ITS CONTRIBUTORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF YOUR ACCESS TO OR USE OF THE SERVICE.
          </p>
        </section>

        {/* 6. Modifications to Terms */}
        <section className="bg-white border border-slate-100 rounded-3xl p-8 shadow-xs space-y-4">
          <h2 className="text-2xl font-extrabold text-slate-900">6. Changes to Terms</h2>
          <p className="text-slate-600 text-sm leading-relaxed">
            We reserve the right to revise or replace these Terms of Service at any time. Changes will be reflected with an updated &quot;Last updated&quot; date at the top of this document. Continued use of Color Magic following changes constitutes acceptance of the new terms.
          </p>
        </section>

        {/* 7. Contact */}
        <section className="bg-gradient-to-r from-purple-500 to-pink-500 rounded-3xl p-8 text-white space-y-3">
          <h2 className="text-2xl font-extrabold flex items-center gap-2">
            <Mail className="w-6 h-6 text-white" /> 7. Contact Us
          </h2>
          <p className="text-white/90 text-sm leading-relaxed">
            If you have questions regarding these Terms of Service, please contact the development team:
          </p>
          <div className="text-sm font-semibold pt-2">
            <p><strong>Organization:</strong> TechKreative</p>
            <p><strong>Website:</strong> <a href="https://techkreative.com" target="_blank" rel="noopener noreferrer" className="underline hover:text-pink-100">https://techkreative.com</a></p>
            <p><strong>Privacy Policy:</strong> <Link href="/privacy" className="underline hover:text-pink-100">View Privacy Policy</Link></p>
          </div>
        </section>
      </div>
    </div>
  );
}
