name: Deploy Cloudflare Testing

on:
  push:
    branches:
      - fixing_cloudflare
    paths-ignore:
      - ".github/workflows/api.yml"
      - ".github/workflows/main.yml"

jobs:
  web-deploy:
    name: 🎉 Sync Main App to Server
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./
          server-dir: ./colormagic/
          exclude: |
            **/.git*
            **/.git*/**
            **/.github*
            **/.github*/**

      - name: 🧹 Purge Cloudflare Cache
        uses: jakejarvis/cloudflare-purge-action@v0.3.0
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
