name: Deployment of Test Branch
on:
  push:
    branches:
      - test
jobs:
  web-deploy:
    name: 🎉 Sync to Server
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # '.' means it will upload everything in your repo root
        local-dir: ./ 
        # Usually public_html/ or public_html/colorsmagic/
        server-dir: ./testColorMagic/
